---
title: "First Knit"
author: "Shael Quintero"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer 
I attended Eastside High School ,where I graduated the year of 2022. English is far from being like math, math is a bit more challenging to me as supposed to english just reading and writing. A subject i did good in was Spanish since its a language I’m already aware of.
  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
 I own a Apple computer and I think I’m pretty familiar with it and i know my way around it.. Id give myself a 7. Im connection is okay not the best, but workable.
 
 
 
 
## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I would like to be called by my government name "Shael"
  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  I want to achieve many goals and challenges and to start off it was to graduate High-school now College. Own many businesses and major in Business.

 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  Ive been to Mexico, specifically Guadalajara, Jalisco. It’s where my Mom is from and we visit once or twice every year. I would choose the Army branch due to my brother already joining, i would get the gist of it.





## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  This is my first time taking 116 and I've never taken 115. I wasn't aware they were different, I plan on obtaining a high score of an A the lowest a C. 
   
 




git config --global user.name “squintero3 “
git config --global user.email “squintero3@students.avc.edu”
git config --global http.sslverify "false" 
git config --global core.autocrlf true
git config --global credential.helper 'cache --timeout 3600

  




